import React from 'react';
import AnchorNTextClient from './Client';

const chapters = [
  { id: "intro", label: "Introduction", content: "<p>Guerric SANT – Développeur Web Indépendant<br />Adresse e-mail : guerric.sant@gmail.com<br />SIRET : 943 600 395 00017</p>" },
  { id: "object", label: "1. Objet", content: "<p>1.1 Les Conditions Générales ont pour objet de régir les relations contractuelles entre Guerric SANT et le Client et définir l’étendue des prestations proposées par Guerric SANT.</p><br /><p>1.2 Les Conditions Générales s’appliquent à toute prestation de toute nature, effectuée par Guerric SANT dans les pays du monde entier. Elles prévalent sur toute autre condition d’achat, sauf dérogation expresse et formelle accordée par Guerric SANT. Elles pourront être modifiées ou complétées si Guerric SANT établit un ou plusieurs éléments contractuels qui, le cas échéant, tiendraient lieu de conditions particulières.</p><br /><p>1.3 Le fait pour une personne physique ou morale, de commander un service ou produit de la société Guerric SANT emporte acceptation pleine et entière des présentes conditions générales de vente.</p><br /><p>1.4 Guerric SANT peut modifier, réactualiser ou rectifier les présentes, notamment afin de prendre en compte une évolution législative, réglementaire, jurisprudentielle et/ou technique. Guerric SANT prévient, dans la mesure du possible, ses Clients de toute modification de ses Conditions Générales. L’actualisation ne concerne en aucun cas les prestations déjà exécutées ou en cours d’exécution, excepté pour celles dont la durée restante est supérieure à six mois à la date de la modification. Dans ce cas, les dernières Conditions Générales sont mises en application entre les parties.</p><br /><p>1.5 Dans le cas où l’une des dispositions des présentes est réputée ou déclarée nulle, ou non écrite, par un tribunal compétent, les autres dispositions restent intégralement en vigueur et doivent être interprétées de façon à respecter l’intention originelle des parties exprimée dans ce document.</p>" },
  { id: "pricing", label: "2. Formation et conditions d’exécution du contrat", content: "<p>2.1 Les prestations proposées par Guerric SANT sont décrites dans les documents contractuels spécifiques et sont exécutées dans les délais prévus. Toute modification ou prolongation des prestations doit être convenue par écrit entre les parties.</p><br /><p>2.2 Les prestations débutent à compter de la réception d'un accord de commande signé et, le cas échéant, d'un acompte correspondant. La durée de l'exécution de chaque prestation est spécifiée dans le devis ou contrat.</p>" },
  { id: "payment", label: "3. Modalités de paiement", content: "<p>3.1 Le prix de la prestation est ferme et définitif. Il est indiqué en euros, hors taxes, et correspond au montant total à régler par le Client.</p><br /><p>3.2 Les prestations proposées sont soumises à deux modalités de paiement distinctes, selon leur nature :</p><ul><li>Prestations opérationnelles : Acompte de 30 % du montant total à la commande, solde dans les 30 jours suivant livraison.</li><li>Prestations d’accompagnement : Paiement intégral avant début de la mission.</li></ul><br /><p>3.3 Les paiements sont exclusivement effectués par virement bancaire. Les coordonnées bancaires sont fournies sur la facture.</p><br /><p>3.4 En cas de retard de paiement, des pénalités de retard seront appliquées à hauteur de 1,5 fois le taux de l'intérêt légal. La prestation peut être suspendue en cas de non-paiement après relances.</p>" },
  { id: "delivery", label: "4. Livraison de la prestation", content: "<p>4.1 La livraison de la prestation se fait au lieu du siège social de Guerric SANT. Sauf indication contraire, elle est réputée effectuée à la date prévue, sauf si une demande écrite de report est faite par le Client au moins 48 heures avant la date prévue.</p><br /><p>4.2 Les prestations sont livrées sous forme numérique, via des canaux électroniques (e-mail, serveur sécurisé, etc.). Le Client doit vérifier la conformité des livrables dès réception.</p><br /><p>4.3 Si le Client tarde à fournir les éléments nécessaires à la réalisation de la prestation, la livraison pourra être retardée.</p>" },
  { id: "liability", label: "5. Obligations et responsabilités de Guerric SANT", content: "<p>5.1 Guerric SANT s'engage à fournir des prestations de qualité, mais ne répond que d'une obligation de moyens.</p><br /><p>5.2 Guerric SANT intervient dans les meilleurs délais en cas de dysfonctionnement résultant de la prestation fournie.</p><br /><p>5.3 Guerric SANT ne pourra être tenu responsable en cas de faute du Client, de négligence, ou d'interruption due à un tiers.</p>" },
  { id: "intellectualProperty", label: "6. Propriétés intellectuelles", content: "<p>6.1 Les éléments fournis par le Client sont sa propriété exclusive. Le Client garantit Guerric SANT contre toute réclamation d'un tiers.</p><br /><p>6.2 Les créations de Guerric SANT restent sa propriété exclusive. Les droits d’exploitation sont cédés au Client à titre non exclusif.</p><br /><p>6.3 Le Client peut modifier le code source, sous réserve de ne pas revendre ou dupliquer les sources. Guerric SANT n’est pas responsable des modifications apportées par le Client.</p>" },
  { id: "property", label: "7. Réserve de propriété", content: "<p>7.1 Guerric SANT conserve la propriété de la prestation jusqu'au paiement intégral du prix.</p><br /><p>7.2 En cas d’interruption définitive de la prestation, Guerric SANT peut vendre ou détruire les éléments de la prestation après information au Client.</p>" },
  { id: "references", label: "8. Utilisation des références", content: "<p>8.1 Guerric SANT se réserve le droit d'utiliser les références du Client dans le cadre de ses activités commerciales, sauf accord contraire écrit de ce dernier.</p>" },
  { id: "privacy", label: "9. Confidentialité", content: "<p>9.1 Chaque partie s’engage à garder confidentielles les informations échangées dans le cadre de la prestation, sauf obligation légale de divulgation.</p>" },
  { id: "law", label: "10. Loi informatique et liberté", content: "<p>Le Client s'engage à accomplir les formalités nécessaires auprès de la CNIL et dispose d'un droit d’accès, de modification et de suppression des informations le concernant, conformément à la loi informatique et liberté du 6 janvier 1978.</p>" },
  { id: "absoluteNecessity", label: "11. Cas de force majeure", content: "<p>La société Guerric SANT n’est pas responsable des retards ou non-exécution dus à un événement de force majeure, tel que défini par le Code Civil.</p>" },
  { id: "employees", label: "12. Non-sollicitation du personnel", content: "<p>Le Client s’engage à ne pas débaucher le personnel de Guerric SANT ayant participé à la réalisation des prestations pour une période de deux ans après la fin de la prestation.</p>" },
  { id: "frenchLaw", label: "13. Droit applicable - attribution de compétence", content: "<p>Les présentes conditions sont soumises au droit français. Tout litige sera de la compétence exclusive des tribunaux du siège de Guerric SANT.</p>" }
];

export default function AnchorNText(): React.ReactElement {
  return <AnchorNTextClient chapters={chapters} />
}
